// Weight action types
export const LOAD_WEIGHTS = "LOAD_WEIGHTS"
export const WEIGHT_UPDATED = "WEIGHT_UPDATED"

// Domain items action types
export const LOAD_DOMAIN_ITEMS = "LOAD_DOMAIN_ITEMS"
export const DOMAIN_ITEM_PRESSED = "DOMAIN_ITEM_PRESSED"
export const SELECT_DOMAIN_ITEM_FOR_COMPARISON = "SELECT_DOMAIN_ITEM_FOR_COMPARISON"
export const TOGGLE_COMPARE_DOMAIN_ITEMS_MODE = "TOGGLE_COMPARE_DOMAIN_ITEMS_MODE"

// Map action types
export const MAP_CLICKED = "MAP_CLICKED"

// UI actions
export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR"
export const SWITCH_THEME = "SWITCH_THEME"