// Weight action types
export const LOAD_WEIGHTS = "LOAD_WEIGHTS"
export const WEIGHT_UPDATED = "WEIGHT_UPDATED"

// Domain items action types
export const SELECT_PRESET_GROUP = "SELECT_PRESET_GROUP"
export const DOMAIN_ITEM_PRESSED = "DOMAIN_ITEM_PRESSED"
export const SELECT_DOMAIN_ITEM_FOR_COMPARISON = "SELECT_DOMAIN_ITEM_FOR_COMPARISON"
export const TOGGLE_COMPARE_DOMAIN_ITEMS_MODE = "TOGGLE_COMPARE_DOMAIN_ITEMS_MODE"
export const CLEAR_ALL_SELECTED_ITEMS_FOR_COMPARISON = "CLEAR_ALL_SELECTED_ITEMS_FOR_COMPARISON"

export const TEXT_FILTER_CLEAN = "TEXT_FILTER_CLEAN"
export const TEXT_FILTER_START_SEARCH = "TEXT_FILTER_START_SEARCH"
export const TEXT_FILTER_FINISH_SEARCH = "TEXT_FILTER_FINISH_SEARCH"
export const TEXT_FILTER_UPDATE_SELECTION = "TEXT_FILTER_UPDATE_SELECTION"
export const LOAD_PRIORITY_PRESETS = "LOAD_PRIORITY_PRESETS"
export const LOAD_FILTER_PRESETS = "LOAD_FILTER_PRESETS"
export const LOAD_GEO_PRESETS = "LOAD_GEO_PRESETS"

// Map action types
export const MAP_CLICKED = "MAP_CLICKED"

// UI actions
export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR"
export const SWITCH_THEME = "SWITCH_THEME"
export const TOGGLE_CREATE_SCENARIO = "TOGGLE_CREATE_SCENARIO"

// Simulation
export const LOAD_SCENARIOS = "LOAD_SCENARIOS"
export const SELECT_SCENARIO = "SELECT_SCENARIO"
export const SELECT_SCENARIO_STEP = "SELECT_SCENARIO_STEP"
export const CREATE_SCENARIO = "CREATE_SCENARIO"