export const COMPARE_DOMAIN_ITMES_OFF = "COMPARE_DOMAIN_ITMES_OFF"
export const COMPARE_DOMAIN_ITMES_SELECT = "COMPARE_DOMAIN_ITMES_SELECT"
export const COMPARE_DOMAIN_ITMES_VIEW = "COMPARE_DOMAIN_ITMES_VIEW"